#' Calculate baseline emissions for ACM0006
#'
#' Computes baseline emissions from heat and electricity that would otherwise be
#' supplied by fossil fuels, reflecting the combined heat and power structure of
#' ACM0006.
#'
#' @param heat_output_tj Useful thermal energy generated by the project in
#'   terajoules.
#' @param baseline_heat_ef Emission factor for displaced thermal energy in
#'   tonnes CO2e per terajoule.
#' @param electricity_output_mwh Net electricity exported to users or the grid
#'   in megawatt-hours. Defaults to 0 when the project is heat-only.
#' @param baseline_electricity_ef Emission factor for displaced electricity in
#'   tonnes CO2e per MWh. Defaults to 0.
#' @return Numeric vector of baseline emissions in tonnes CO2e.
#' @examples
#' calculate_baseline_emissions_acm0006(10, 80, 500, 0.75)
#' @export
calculate_baseline_emissions_acm0006 <- function(heat_output_tj,
                                                 baseline_heat_ef,
                                                 electricity_output_mwh = 0,
                                                 baseline_electricity_ef = 0) {
  if (!is.numeric(heat_output_tj) || any(heat_output_tj < 0)) {
    rlang::abort("`heat_output_tj` must be a non-negative numeric vector.")
  }
  if (!is.numeric(baseline_heat_ef) || any(baseline_heat_ef < 0)) {
    rlang::abort("`baseline_heat_ef` must be a non-negative numeric vector.")
  }
  if (!(length(baseline_heat_ef) %in% c(1, length(heat_output_tj)))) {
    rlang::abort("`baseline_heat_ef` must be length 1 or match `heat_output_tj`.")
  }
  if (!is.numeric(electricity_output_mwh) || any(electricity_output_mwh < 0)) {
    rlang::abort("`electricity_output_mwh` must be a non-negative numeric vector.")
  }
  if (!is.numeric(baseline_electricity_ef) || any(baseline_electricity_ef < 0)) {
    rlang::abort("`baseline_electricity_ef` must be a non-negative numeric vector.")
  }
  if (!(length(baseline_electricity_ef) %in% c(1, length(electricity_output_mwh)))) {
    rlang::abort("`baseline_electricity_ef` must be length 1 or match `electricity_output_mwh`.")
  }

  heat_output_tj * baseline_heat_ef + electricity_output_mwh * baseline_electricity_ef
}

#' Calculate project emissions for ACM0006
#'
#' Aggregates project emissions from auxiliary fossil fuel use, electricity
#' imports, and transport of biomass feedstock.
#'
#' @param auxiliary_fossil_tj Auxiliary fossil fuel consumption in terajoules.
#' @param auxiliary_fossil_ef Emission factor for auxiliary fuel in tonnes CO2e
#'   per terajoule.
#' @param electricity_import_mwh Electricity imported from the grid in
#'   megawatt-hours.
#' @param import_emission_factor Emission factor for imported electricity in
#'   tonnes CO2e per MWh.
#' @param biomass_transport_tkm Biomass transport activity in tonne-kilometres.
#' @param transport_emission_factor Emission factor for biomass transport in
#'   tonnes CO2e per tonne-kilometre.
#' @return Numeric vector of project emissions in tonnes CO2e.
#' @examples
#' calculate_project_emissions_acm0006(0.2, 74, 20, 0.7, 500, 0.0001)
#' @export
calculate_project_emissions_acm0006 <- function(auxiliary_fossil_tj,
                                                auxiliary_fossil_ef,
                                                electricity_import_mwh = 0,
                                                import_emission_factor = 0,
                                                biomass_transport_tkm = 0,
                                                transport_emission_factor = 0) {
  if (!is.numeric(auxiliary_fossil_tj) || any(auxiliary_fossil_tj < 0)) {
    rlang::abort("`auxiliary_fossil_tj` must be a non-negative numeric vector.")
  }
  if (!is.numeric(auxiliary_fossil_ef) || any(auxiliary_fossil_ef < 0)) {
    rlang::abort("`auxiliary_fossil_ef` must be a non-negative numeric vector.")
  }
  if (!(length(auxiliary_fossil_ef) %in% c(1, length(auxiliary_fossil_tj)))) {
    rlang::abort("`auxiliary_fossil_ef` must be length 1 or match `auxiliary_fossil_tj`.")
  }
  if (!is.numeric(electricity_import_mwh) || any(electricity_import_mwh < 0)) {
    rlang::abort("`electricity_import_mwh` must be a non-negative numeric vector.")
  }
  if (!is.numeric(import_emission_factor) || any(import_emission_factor < 0)) {
    rlang::abort("`import_emission_factor` must be a non-negative numeric vector.")
  }
  if (!(length(import_emission_factor) %in% c(1, length(electricity_import_mwh)))) {
    rlang::abort("`import_emission_factor` must be length 1 or match `electricity_import_mwh`.")
  }
  if (!is.numeric(biomass_transport_tkm) || any(biomass_transport_tkm < 0)) {
    rlang::abort("`biomass_transport_tkm` must be a non-negative numeric vector.")
  }
  if (!is.numeric(transport_emission_factor) || any(transport_emission_factor < 0)) {
    rlang::abort("`transport_emission_factor` must be a non-negative numeric vector.")
  }
  if (!(length(transport_emission_factor) %in% c(1, length(biomass_transport_tkm)))) {
    rlang::abort("`transport_emission_factor` must be length 1 or match `biomass_transport_tkm`.")
  }

  auxiliary_fossil_tj * auxiliary_fossil_ef +
    electricity_import_mwh * import_emission_factor +
    biomass_transport_tkm * transport_emission_factor
}

#' Calculate leakage emissions for ACM0006
#'
#' Estimates leakage from competing biomass uses or market shifts by applying a
#' leakage fraction to the baseline emissions.
#'
#' @param leakage_fraction Numeric vector (0 to 1) representing the fraction of
#'   baseline emissions attributed to leakage.
#' @param baseline_emissions Baseline emissions associated with the monitoring
#'   data in tonnes CO2e.
#' @return Numeric vector of leakage emissions in tonnes CO2e.
#' @examples
#' calculate_leakage_emissions_acm0006(0.05, 1000)
#' @export
calculate_leakage_emissions_acm0006 <- function(leakage_fraction,
                                                baseline_emissions) {
  if (!is.numeric(leakage_fraction) || any(leakage_fraction < 0 | leakage_fraction > 1)) {
    rlang::abort("`leakage_fraction` must be numeric between 0 and 1.")
  }
  if (!is.numeric(baseline_emissions) || any(baseline_emissions < 0)) {
    rlang::abort("`baseline_emissions` must be a non-negative numeric vector.")
  }
  if (!(length(leakage_fraction) %in% c(1, length(baseline_emissions)))) {
    rlang::abort("`leakage_fraction` must be length 1 or match `baseline_emissions`.")
  }

  leakage_fraction * baseline_emissions
}

#' Calculate emission reductions for ACM0006
#'
#' Derives emission reductions by subtracting project and leakage emissions from
#' baseline emissions.
#'
#' @param baseline_emissions Baseline emissions in tonnes CO2e.
#' @param project_emissions Project emissions in tonnes CO2e.
#' @param leakage_emissions Leakage emissions in tonnes CO2e. Defaults to zero.
#' @return Numeric vector of emission reductions in tonnes CO2e.
#' @examples
#' calculate_emission_reductions_acm0006(1200, 150, 30)
#' @export
calculate_emission_reductions_acm0006 <- function(baseline_emissions,
                                                  project_emissions,
                                                  leakage_emissions = 0) {
  if (!is.numeric(baseline_emissions)) {
    rlang::abort("`baseline_emissions` must be numeric.")
  }
  if (!is.numeric(project_emissions)) {
    rlang::abort("`project_emissions` must be numeric.")
  }
  if (!is.numeric(leakage_emissions)) {
    rlang::abort("`leakage_emissions` must be numeric.")
  }

  baseline_emissions - project_emissions - leakage_emissions
}
