
PDDXAschemaV2UI <- function(id, 
                            lsPreset = NULL, 
                            hL = 4, 
                            colWidth = 12, 
                            inpWidth = DEFAULT_INP_WIDTH,
                            idSchemaV = NULL) {
  
  ns <- NS(id)
  
  tagList(
    
    #useShinyjs(),
    
    GtextOutput(id = ns("title_project"), 
                title = "Project Title", 
                hL = hL, 
                colWidth = colWidth),
    
    GtextOutput(id = ns("id_project"), 
                title = "Project ID", 
                hL = hL, 
                colWidth = colWidth),
    
    GtextOutput(id = ns("toDRPLA"), 
                title = "Approving DR-PLA of Project", 
                hL = hL, 
                colWidth = colWidth),
    
    chooseLicenseInput(
      id = ns('chLicPDL'),
      title = "Project Developer License",
      helpTxt = "Select your Independent Impact Project Developer License (II-L-PD) to use for this project."),
    
    GtextAreaInput(id = ns('purpose_project'),
                   title = 'Project Purpose',
                   helpTxt = "What is the purpose of the project activity? (100 chars. min.)",
                   value = lsPreset$purpose_project,
                   resize = 'vertical',
                   hL = hL,
                   colWidth = colWidth,
                   inpWidth = inpWidth),
    
    wellPanel(
      h4("Project Location"),
      helpText("Where will the project activity take place? Please provide a shapefile of the location. If your project will take place across multiple locations, please provide a shapefile for each location."),
      dynamicMultiV2Input(id = ns('location_project'),
                          useModal = FALSE,
                          nmUImod = "locationInput",
                          lsArgsModUI = list(hL = 5, 
                                             colWidth = 12, 
                                             inpWidth = DEFAULT_INP_WIDTH)),
      textOutput(outputId = ns("location_project_msg"))),
    
    # GdynamicMultiInput(id = ns('location_project'), 
    #                    title = 'Project Location', 
    #                    helpTxt = "Where will the project activity take place? Please provide the IPFS URL of a shapefile of the location. If your project will take place across multiple locations, please repeat this question for each location.",
    #                    hL = hL,
    #                    colWidth = colWidth,
    #                    inpWidth = inpWidth),
    
    wellPanel(
      h4("Technologies and Measures"),
      helpText("What technologies and/or measures will be employed or implemented by the project activity to achieve its purpose?"),
      dynamicMultiV2Input(id = ns('techmeas_project'), 
                          useModal = FALSE,
                          nmUImod = 'technologyOrMeasureInput', 
                          lsArgsModUI = list(hL = 5, colWidth = 12, inpWidth = DEFAULT_INP_WIDTH)),
      textOutput(outputId = ns("techmeas_project_msg"))),
    
    # GdynamicMultiInput(id = ns('techmeas_project'),
    #                    title = 'Technologies and Measures',
    #                    helpTxt = "What technologies and/or measures will be employed or implemented by the project activity to achieve its purpose?",
    #                    hL = hL,
    #                    colWidth = colWidth,
    #                    inpWidth = inpWidth),
    
    wellPanel(
      h4('Project Parties and Participants'),
      helpText("Who are the parties involved in the project?"),
      dynamicMultiV2Input(id = ns('parties_project'), 
                          useModal = FALSE,
                          nmUImod = 'projectPartyInput', 
                          lsArgsModUI = list(hL = 5, colWidth = 12, inpWidth = DEFAULT_INP_WIDTH)),
      textOutput(outputId = ns("parties_project_msg"))),
    
    # GdynamicMultiInput(id = ns('parties_project'),
    #                    title = 'Project Parties and Participants',
    #                    helpTxt = "Who are the parties involved in the project?",
    #                    hL = hL,
    #                    colWidth = colWidth,
    #                    inpWidth = inpWidth),
    
    GtextAreaInput(id = ns('eligibility_project'),
                   title = 'Project Eligibility',
                   helpTxt = "Eligibility of project. (Optional.)",
                   value = lsPreset$eligibility_project,
                   resize = 'vertical',
                   hL = hL,
                   colWidth = colWidth,
                   inpWidth = inpWidth),
    
    GtextAreaInput(id = ns('legal_matters'),
                   title = 'Legal Matters',
                   helpTxt = "Legal ownership of products generated by the project and legal rights to use or alter resources required to service the project. (100 chars. min.)",
                   value = lsPreset$legal_matters,
                   resize = 'vertical',
                   hL = hL,
                   colWidth = colWidth,
                   inpWidth = inpWidth),
    
    GselectInput(id = ns('status_public_funding'),
                 title = 'Public Funding',
                 helpTxt = "Does this project receive any public funding?",
                 choices = c('YES', 'NO'),
                 selected = lsPreset$status_public_funding,
                 hL = hL,
                 colWidth = colWidth,
                 inpWidth = inpWidth),
    
    wellPanel(
      h4('Public Funding Source'),
      helpText("Details of the public funding source."),
      dynamicMultiV2Input(id = ns('source_public_funding'), 
                          useModal = FALSE,
                          nmUImod = 'fundingSourceInput', 
                          lsArgsModUI = list(hL = 5, colWidth = 12, inpWidth = DEFAULT_INP_WIDTH)),
      textOutput(outputId = ns("source_public_funding_msg"))),
    
    # GdynamicMultiInput(id = ns('source_public_funding'),
    #                    title = 'Public Funding Source',
    #                    helpTxt = "Details of the public funding source.",
    #                    hL = hL,
    #                    colWidth = colWidth,
    #                    inpWidth = inpWidth),
    
    GtextAreaInput(id = ns('history_project'),
                   title = 'Project History',
                   helpTxt = "History of project activity. (100 chars. min.)",
                   value = lsPreset$history_project,
                   resize = 'vertical',
                   hL = hL,
                   colWidth = colWidth,
                   inpWidth = inpWidth),
    
    GtextAreaInput(id = ns('debundling'),
                   title = 'Debundling',
                   helpTxt = "Debundling. (100 chars. min.)",
                   value = lsPreset$debundling,
                   resize = 'vertical',
                   hL = hL,
                   colWidth = colWidth,
                   inpWidth = inpWidth),
    
    textOutput(outputId = ns("toInvalidInput")),
    
    br())
  
  
}

PDDXAschemaV2Server <- function(id,  
                                dbCon,
                                loginInfoUsr,
                                idEntity,
                                idWorkflow = NULL,
                                idSchema = NULL,
                                lsPreset = NULL) {
  
  moduleServer(
    id = id, 
    function(input, output, session) {
      
      ns <- session$ns
      
      rvToReturn <- reactiveValues()
      rvToReturn$allResultsGood <- FALSE
      rvToReturn$results <- reactiveValues(
        headers = list(
          id_msg_lic = NULL,
          url_ipfs_lic = NULL,
          id_msg_pred = NULL,
          url_ipfs_pred = NULL,
          id_subject = idEntity,
          type_subject = "PROJECT"),
        title_project = NULL,
        purpose_project = NULL,
        location_project = NULL,
        techmeas_project = NULL,
        parties_project = NULL,
        eligibility_project = NULL,
        legal_matters = NULL,
        status_public_funding = NULL,
        source_public_funding = NULL,
        history_project = NULL,
        debundling = NULL)
      
      resultsGood <- reactiveValues()
      resultsGood$headers <- FALSE      
      resultsGood$title_project <- FALSE
      resultsGood$purpose_project <- FALSE
      resultsGood$location_project <- FALSE
      resultsGood$techmeas_project <- FALSE
      resultsGood$parties_project <- FALSE
      resultsGood$eligibility_project <- FALSE
      resultsGood$legal_matters <- FALSE
      resultsGood$status_public_funding <- FALSE
      resultsGood$source_public_funding <- FALSE
      resultsGood$history_project <- FALSE
      resultsGood$debundling <- FALSE
      
      outputMsgs <- reactiveValues()
      outputMsgs$purpose_project <- ''
      outputMsgs$location_project <- ''
      outputMsgs$techmeas_project <- ''
      outputMsgs$parties_project <- ''
      outputMsgs$eligibility_project <- ''
      outputMsgs$legal_matters <- ''
      outputMsgs$status_public_funding <- ''
      outputMsgs$source_public_funding <- ''
      outputMsgs$history_project <- ''
      outputMsgs$debundling <- ''
      
      rvOther <- reactiveValues()
      
      # preset inputs ----------------------------------------------------------
      
      if ('purpose_project' %in% names(lsPreset)) {
        updateTextAreaInput(session = session, 
                            inputId = 'purpose_project', 
                            value = lsPreset$purpose_project)
      }
      
      if ('eligibility_project' %in% names(lsPreset)) {
        updateTextAreaInput(session = session, 
                            inputId = 'eligibility_project', 
                            value = lsPreset$eligibility_project)
      }
      
      if ('legal_matters' %in% names(lsPreset)) {
        updateTextAreaInput(session = session, 
                            inputId = 'legal_matters', 
                            value = lsPreset$legal_matters)
      }
      
      if ('status_public_funding' %in% names(lsPreset)) {
        updateSelectInput(session = session, 
                          inputId = 'status_public_funding', 
                          selected = lsPreset$status_public_funding)
      }
      
      if ('history_project' %in% names(lsPreset)) {
        updateTextAreaInput(session = session, 
                            inputId = 'history_project', 
                            value = lsPreset$history_project)
      }
      
      if ('debundling' %in% names(lsPreset)) {
        updateTextAreaInput(session = session, 
                            inputId = 'debundling', 
                            value = lsPreset$debundling)
      }
      
      # module servers ---------------------------------------------------------
      
      modSrvrs <- reactiveValues()
      
      modSrvrs$mProjDevLic <- chooseLicenseServer(
        id = "chLicPDL",
        dbCon = dbCon,
        scopes = "PROJECT_DEVELOPER", 
        statuses = "ACTIVE",
        idAgent = loginInfoUsr$id_agent,
        lsPreset = NULL) # TODO: implement lsPreset
      
      modSrvrs$location_project <- dynamicMultiV2Server(
        id = 'location_project', 
        nmUImod = "locationInput",
        nmSrvrMod = 'locationServer',
        btns = c('edit', 'remove'), 
        lsPreset = lsPreset$location_project, 
        lsArgsModSrvr = list(uploadToIPFS = TRUE),
        useModal = FALSE)
      
      modSrvrs$techmeas_project <- dynamicMultiV2Server(
        id = 'techmeas_project', 
        nmUImod = 'technologyOrMeasureInput', 
        nmSrvrMod = 'technologyOrMeasureServer', 
        btns = c('edit', 'remove'), 
        lsPreset = lsPreset$techmeas_project,
        lsArgsModSrvr = NULL,
        useModal = FALSE)
      
      modSrvrs$parties_project <- dynamicMultiV2Server(
        id = 'parties_project', 
        nmUImod = 'projectPartyInput', 
        nmSrvrMod = 'projectPartyServer', 
        btns = c('edit', 'remove'), 
        lsPreset = lsPreset$parties_project,
        lsArgsModSrvr = NULL,
        useModal = FALSE)
      
      modSrvrs$source_public_funding <- dynamicMultiV2Server(
        id = 'source_public_funding', 
        nmUImod = 'fundingSourceInput', 
        nmSrvrMod = 'fundingSourceServer', 
        btns = c('edit', 'remove'), 
        lsPreset = lsPreset$source_public_funding,
        lsArgsModSrvr = NULL,
        useModal = FALSE)
      
      # inputs -----------------------------------------------------------------
      
      observe({
        rvToReturn$results$headers$id_msg_lic <- modSrvrs$mProjDevLic$results$id_msg
        rvToReturn$results$headers$url_ipfs_lic <- modSrvrs$mProjDevLic$results$url_ipfs
      })
      
      observe({
        
        resultsGood$headers <- FALSE
        
        if (!isValidInput.text(
          x = rvToReturn$results$headers$id_msg_pred, 
          bRequired = TRUE, 
          nCharMin = 5, 
          nCharMax = 100)) {
          return(invisible(0))
        }
        
        if (!isValidInput.text(
          x = rvToReturn$results$headers$url_ipfs_pred, 
          bRequired = TRUE, 
          nCharMin = 5, 
          nCharMax = 100)) {
          return(invisible(0))
        }
        
        if (!modSrvrs$mProjDevLic$allResultsGood) {
          return(invisible(3))
        }
        
        resultsGood$headers <- TRUE
      })
      
      observeEvent(input$purpose_project, handlerExpr = {
        
        resultsGood$purpose_project <- FALSE
        rvToReturn$results$purpose_project <- input$purpose_project
        
        nChar <- nchar(input$purpose_project)
        outputMsgs$purpose_project <- sprintf('%d chars. remaining', 1000 - nChar)
        
        resultsGood$purpose_project <- isValidInput.text(
          x = input$purpose_project, 
          bRequired = TRUE, 
          nCharMin = 100, 
          nCharMax = 1000) 
        
      })
      
      observeEvent(modSrvrs$location_project$items, handlerExpr = {
        
        resultsGood$location_project <- FALSE
        outputMsgs$location_project <- ''
        rvToReturn$results$location_project <- modSrvrs$location_project$items
        resultsGood$location_project <- length(modSrvrs$location_project$items) > 0
        if (!resultsGood$location_project) {
          outputMsgs$location_project <- '*Required.'
        }
        
      })
      
      observeEvent(modSrvrs$techmeas_project$items, handlerExpr = {
        
        resultsGood$techmeas_project <- FALSE
        outputMsgs$techmeas_project <- ''
        rvToReturn$results$techmeas_project <- modSrvrs$techmeas_project$items
        resultsGood$techmeas_project <- length(modSrvrs$techmeas_project$items) > 0
        if (!resultsGood$techmeas_project) {
          outputMsgs$techmeas_project <- '*Required.'
        }
        
      })
      
      observeEvent(modSrvrs$parties_project$items, handlerExpr = {
        
        resultsGood$parties_project <- FALSE
        outputMsgs$parties_project <- ''
        rvToReturn$results$parties_project <- modSrvrs$parties_project$items
        resultsGood$parties_project <- length(modSrvrs$parties_project$items) > 0
        if (!resultsGood$parties_project) {
          outputMsgs$parties_project <- '*Required.'
        }
        
      })
      
      observeEvent(input$eligibility_project, handlerExpr = {
        
        resultsGood$eligibility_project <- FALSE
        rvToReturn$results$eligibility_project <- input$eligibility_project
        
        nChar <- nchar(input$eligibility_project)
        outputMsgs$eligibility_project <- sprintf('%d chars. remaining', 1000 - nChar)
        
        resultsGood$eligibility_project <- isValidInput.text(
          x = input$eligibility_project, 
          bRequired = FALSE, 
          nCharMin = 0, 
          nCharMax = 1000) 
        
      })
      
      observeEvent(input$legal_matters, handlerExpr = {
        
        resultsGood$legal_matters <- FALSE
        rvToReturn$results$legal_matters <- input$legal_matters
        
        nChar <- nchar(input$legal_matters)
        outputMsgs$legal_matters <- sprintf('%d chars. remaining', 1000 - nChar)
        
        resultsGood$legal_matters <- isValidInput.text(
          x = input$legal_matters, 
          bRequired = TRUE, 
          nCharMin = 100, 
          nCharMax = 1000) 
        
      })
      
      observeEvent(input$status_public_funding, handlerExpr = {
        
        resultsGood$status_public_funding <- FALSE
        outputMsgs$status_public_funding <- ''
        rvToReturn$results$status_public_funding <- input$status_public_funding
        validate(need(input$status_public_funding, message = FALSE))
        if (length(input$status_public_funding) == 0) { return(invisible(NULL)) }
        resultsGood$status_public_funding <- TRUE
        
      })
      
      observeEvent(modSrvrs$source_public_funding$items, handlerExpr = {
        
        outputMsgs$source_public_funding <- ''
        rvToReturn$results$source_public_funding <- modSrvrs$source_public_funding$items
        
      })
      
      observe({
        validate(need(input$status_public_funding, message = FALSE))
        if (length(input$status_public_funding) == 0) { return(invisible(NULL)) }
        if (input$status_public_funding == "YES") {
          resultsGood$source_public_funding <- length(rvToReturn$results$source_public_funding) > 0
        } else {
          rvToReturn$results$source_public_funding <- NULL
          resultsGood$source_public_funding <- TRUE
        }
      })
      
      observeEvent(input$history_project, handlerExpr = {
        
        resultsGood$history_project <- FALSE
        rvToReturn$results$history_project <- input$history_project
        
        nChar <- nchar(input$history_project)
        outputMsgs$history_project <- sprintf('%d chars. remaining', 1000 - nChar)
        
        resultsGood$history_project <- isValidInput.text(
          x = input$history_project, 
          bRequired = TRUE, 
          nCharMin = 100, 
          nCharMax = 1000) 
        
      })
      
      observeEvent(input$debundling, handlerExpr = {
        
        resultsGood$debundling <- FALSE
        rvToReturn$results$debundling <- input$debundling
        
        nChar <- nchar(input$debundling)
        outputMsgs$debundling <- sprintf('%d chars. remaining', 1000 - nChar)
        
        resultsGood$debundling <- isValidInput.text(
          x = input$debundling, 
          bRequired = TRUE, 
          nCharMin = 100, 
          nCharMax = 1000) 
        
      })
      
      # outputs ----------------------------------------------------------------
      
      output$title_project <- renderText({
        
        tryCatch({
          
          rvToReturn$results$title_project <- dbFetch(
            dbSendQuery(
              conn = dbCon, 
              statement = sprintf("SELECT title FROM tbl_projects WHERE id = '%s';",
                                  idEntity)))[["title"]]
          
          resultsGood$title_project <- TRUE
          
        }, error = function(e) {
          warning(e)
          rvToReturn$results$title_project <- NULL
          resultsGood$title_project <- FALSE
        })
        
        rvToReturn$results$title_project
        
      })
      
      output$id_project <- renderText({
        rvToReturn$results$headers$id_subject
      })
      
      output$toDRPLA <- renderText({
        
        noDocMsg <- "You do not seem to have an approved Project Listing Application (PLA) for this project yet. Please use the 'Independent Impact - Main Workflow' to apply for project listing."
        
        dfDocMd <- getApprovingDRPLAs(
          dbCon = dbCon,
          idProject = idEntity)
        if (length(dfDocMd) == 0) {
          return(noDocMsg)
        }
        
        rvToReturn$results$headers$id_msg_pred <- dfDocMd$id_message_h
        rvToReturn$results$headers$url_ipfs_pred <- dfDocMd$uri_ipfs
        resultsGood$id_msg_pred <- TRUE
        resultsGood$url_ipfs_pred <- TRUE
        
        return(dfDocMd$uri_ipfs)
        
      })
      
      output$purpose_project_msg <- renderText({
        outputMsgs$purpose_project
      })
      
      output$location_project_msg <- renderText({
        outputMsgs$location_project
      })
      
      output$techmeas_project_msg <- renderText({
        outputMsgs$techmeas_project
      })
      
      output$parties_project_msg <- renderText({
        outputMsgs$parties_project
      })
      
      output$eligibility_project_msg <- renderText({
        outputMsgs$eligibility_project
      })
      
      output$legal_matters_msg <- renderText({
        outputMsgs$legal_matters
      })
      
      output$status_public_funding_msg <- renderText({
        outputMsgs$status_public_funding
      })
      
      output$source_public_funding_msg <- renderText({
        outputMsgs$source_public_funding
      })
      
      output$history_project_msg <- renderText({
        outputMsgs$history_project
      })
      
      output$debundling_msg <- renderText({
        outputMsgs$debundling
      })
      
      output$toInvalidInput <- renderText({
        
        if (rvToReturn$allResultsGood) { return(NULL) }
        
        return(
          sprintf("Your inputs to the following fields are not valid: %s",
                  paste(names(resultsGood)[!unlist(reactiveValuesToList(resultsGood))], sep = "", collapse = ", ")))
        
      })
      
      # return logic -----------------------------------------------------------
      
      observe({
        rvToReturn$allResultsGood <- all(unlist(reactiveValuesToList(resultsGood)))
      })
      
      return(rvToReturn)
      
    })
}
